version: 2.1

jobs:
  greeting:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - run:
        name: Greeting
        command: echo "Hello"

workflows:
  example-workflow:
    jobs:
      - greeting
