version: 2.1

orbs:
  cypress: cypress-io/cypress@1

jobs:
  build:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - checkout
      - run:
          name: Branch Contents
          command: ls -al
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Build
          command: npm run build

workflows:
  ci: # ci workflow
    jobs:
      - cypress/install:
          build: npm run build
      - cypress/run:
          requires:
            - cypress/install
          group: "all tests" # name this group "all tests" on the dashboard
          start: "npm start" # start server before running tests

