version: 2.1

orbs:
  cypress: cypress-io/cypress@1
  heroku: circleci/heroku@1.2.6

jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  ci:
    jobs:
      - cypress/install:
          build: npm run build # build application
          filters:
            branches:
              ignore: main
      - cypress/run:
          requires:
            - cypress/install
          group: "all tests" # name this group "all tests" on the dashboard
          start: "npm start" # start server before running tests
          filters:
            branches:
              ignore: main
      - deploy:
          filters:
            branches:
              only: main
