version: 2.1

orbs:
  cypress: cypress-io/cypress@1
  heroku: circleci/heroku@1.2.6

jobs:
  greeting:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - run:
          name: Greeting
          command: echo "Hello"
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: branda-admin-panel-ci-test

workflows:
  ci:
    jobs:
      - greeting
      - deploy:
          requires:
            - greeting
          filters:
            branches:
              only: main
