name: API Tests

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  api:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 8091-8095:8091-8095
          - 11210:11210
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node/latest
      - run: npm install
      # - run: npm run test:api:all