name: Daily Cron Jobs

on:
  schedule:
    - cron: "30 */12 * * *"
  
jobs:
  updateDiningHours:
    runs-on: ubuntu-latest
    steps:
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
      - run: |
        curl --request PATCH -H "api_token: $API_TOKEN" --url https://branda-admin-panel.herokuapp.com/api/cron/updateDiningHours
  updateNews:
    runs-on: ubuntu-latest
    steps:
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
      - run: |
        curl --request PATCH -H "api_token: $API_TOKEN" --url https://branda-admin-panel.herokuapp.com/api/cron/updateNews
    