name: 15-Minute Basis Cron Jobs

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  replaceTags:
    runs-on: ubuntu-latest
    steps:
      - name: Run replace tags cron job
      run: |
        curl --request PATCH -H "api_token: $API_TOKEN" --url https://branda-admin-panel.herokuapp.com/api/cron/replaceTags
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}