name: Utils

on: [push, pull_request]
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  dateUtils:
    runs-on: ubuntu-latest
    env:
      UTIL: dateUtils
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node/latest
      - run: npm install
      - run: npm run test:utils

  dbConnect:
    runs-on: ubuntu-latest
    env:
      UTIL: dbConnect
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node/latest
      - run: npm install
      - run: npm run test:utils

  httpUtils:
    runs-on: ubuntu-latest
    env:
      UTIL: httpUtils
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node/latest
      - run: npm install
      - run: npm run test:utils

  passwordUtils:
    runs-on: ubuntu-latest
    env:
      UTIL: passwordUtils
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node/latest
      - run: npm install
      - run: npm run test:utils

  scheduleUtils:
    runs-on: ubuntu-latest
    env:
      UTIL: scheduleUtils
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node/latest
      - run: npm install
      - run: npm run test:utils

  apiUtils:
    runs-on: ubuntu-latest
    services:
          mongodb:
            image: mongo:latest
            ports:
              - "27017:27017"
    env:
      ADMIN_PANEL_DATABASE_URL: 'mongodb://localhost:27017/testing'
      API_TOKEN_SECRET: '16'
      ADMIN_PANEL_JWT_SECRET: '17'
      ADMIN_PANEL_SECRET: '18'
      SAMSARA_API_KEY: 'abc'
      NEXTAUTH_URL: 'http://localhost:3000'
		  DB_ACCESS_TOKEN_SECRET: 'def'
      UTIL: apiUtils
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node latest
        uses: ./.github/actions/node/latest

      - name: Install dependencies and node-fetch for testing
        run: npm install && npm i node-fetch

      - name: Run Server
        run: npm run dev &

      # - name: Seed test data in MongoDB
      #   run: node seed.js

      - name: Run API tests
        run: npm run test:utils
